name: Build

on:
  push:
    branches:
      - master
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

env:
  IMAGE_NAME: ghcr.io/hoverkraft-tech/helm-push
  PLATFORMS: linux/amd64

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Determine tag or commit
        uses: haya14busa/action-cond@v1
        id: refortag
        with:
          cond: ${{ startsWith(github.ref, 'refs/tags/') }}
          if_true: ${{ github.ref }}
          if_false: latest

      - name: Determine image tag
        id: imagetag
        run: echo "::set-output name=value::${TAG_OR_BRANCH##*/}"
        env:
          TAG_OR_BRANCH: ${{ steps.refortag.outputs.value }}

      - name: Login to github container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCRIO_USERNAME }}
          password: ${{ secrets.GHCRIO_PASSWORD }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          tags: ${{ env.IMAGE_NAME }}:${{ steps.imagetag.outputs.value }}
          file: Dockerfile
          platforms: ${{ env.PLATFORMS }}
          push: true
